### PR TITLE
add translation for Chinese

### PR DESCRIPTION
**Pull request by wangshijun**
add translation for Chinese

### CODE REVIEW

**Comment by michaelrambeau** [comment]
@wangshijun Thank you very much, you did a great job 👍 

I have merged `master` into `develop` branch, because `develop` branch is automatically deployed on netlify.com.

Here is the URL to test the `develop` branch: https://risingstars2016.netlify.com/

The page in Chinese looks good, thank you for your hard work!

Before rebuilding the page in production, I'm going to make a few changes, because I'd like to add your avatar at the end of the page.

**Comment by michaelrambeau** [comment]
Hello again @wangshijun ,
I have just made 2 changes on `develop` branch:

* I fixed the link at the end of the English page (`/cn/` => `zh` )
* I added a section about you at the end of the page in Chinese

Check here https://risingstars2016.netlify.com/zh/

Could you tell me what you want to be displayed for your bio?
I can change your avatar, too, if you want.

image

Thank you!

**Comment by wangshijun** [comment]
Hi, @michaelrambeau 

Thanks for the quick response!

My bio info maybe displayed as flowing:

```
  {
    name: '王仕军',
    url: 'https://zhuanlan.zhihu.com/feweekly',
    avatar: 'https://avatars2.githubusercontent.com/u/719985?v=3&s=88',
    bio1: <span><a href="https://zhuanlan.zhihu.com/feweekly">前端周刊</a>创办者</span>,
    role: 'translation'
  }
```

the avatar size can be changed to meet display requirements.

**Comment by michaelrambeau** [comment]
OK @wangshijun Please check again, I have just updated the test version on Netlify:

https://risingstars2016.netlify.com/zh/

**Comment by wangshijun** [comment]
@michaelrambeau the  bio info is confirmed, thanks!

**Comment by michaelrambeau** [comment]
Alright @wangshijun I deployed the page in Chinese, it's live!

https://risingstars2016.js.org/zh/

**Comment by zxhycxq** [comment]
我只是想过，没有行动。

**Pull request merged**
